#!/usr/bin/env python3

from pathlib import Path
import runpy

from ament_index_python.packages import get_package_share_directory


def main():
    share_dir = Path(get_package_share_directory("dominoes"))
    script_path = share_dir / "dominoes" / "pickup.py"
    runpy.run_path(str(script_path), run_name="__main__")


if __name__ == "__main__":
    main()
