<?xml version="1.0"?>
<package format="3">
  <name>dominoes</name>
  <version>0.0.0</version>
  <description>ROS2 package for precomputing and serving domino pickup joint targets.</description>
  <maintainer email="samdong@example.com">samdong</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>

  <depend>ament_index_python</depend>
  <depend>rclpy</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
